before_script:
  - cp config/database.peak_flow.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load RAILS_ENV=test
services:
  firefox:
    image: fhriley/firefox
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
